# Site settings
title: Modest Crab - Jill Burnham
description: > # this means to ignore newlines until "baseurl:"
  My log on life and tech, travel.I am also a Music buff. Social media ninja. General coffee maven. Organizer. Total pop culture evangelist. yada yada ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://modestcrab.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
